[org-bullets]
src.git="https://github.com/nvim-orgmode/org-bullets.nvim"
fetch.github="nvim-orgmode/org-bullets.nvim"

[neotree]
src.git="https://github.com/nvim-neo-tree/neo-tree.nvim"
fetch.github="nvim-neo-tree/neo-tree.nvim"

[telescope-orgmode]
src.git="https://github.com/nvim-orgmode/telescope-orgmode.nvim"
fetch.github="nvim-orgmode/telescope-orgmode.nvim"

[org-roam]
src.git = "https://github.com/chipsenkbeil/org-roam.nvim"
fetch.github = "chipsenkbeil/org-roam.nvim"

[nvim-base-16]
src.git = "https://github.com/RRethy/nvim-base16"
fetch.github = "RRethy/nvim-base16"
