[org-bullets]
src.git="https://github.com/nvim-orgmode/org-bullets.nvim"
fetch.github="nvim-orgmode/org-bullets.nvim"

[neotree]
src.git="https://github.com/nvim-neo-tree/neo-tree.nvim"
fetch.github="nvim-neo-tree/neo-tree.nvim"

[telescope-orgmode]
src.git="https://github.com/nvim-orgmode/telescope-orgmode.nvim"
fetch.github="nvim-orgmode/telescope-orgmode.nvim"

[nvim-colorizer]
src.git="https://github.com/NvChad/nvim-colorizer.lua"
fetch.github="NvChad/nvim-colorizer.lua"
