# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neotree = {
    pname = "neotree";
    version = "974bbd434c25dc625185571b0455c831cfdde067";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "974bbd434c25dc625185571b0455c831cfdde067";
      fetchSubmodules = false;
      sha256 = "sha256-LP3liN6SVkXzev0SzfH8jPl67wNWqbpBZKk3wvE0doo=";
    };
    date = "2024-05-31";
  };
  nvim-colorizer = {
    pname = "nvim-colorizer";
    version = "85855b38011114929f4058efc97af1059ab3e41d";
    src = fetchFromGitHub {
      owner = "NvChad";
      repo = "nvim-colorizer.lua";
      rev = "85855b38011114929f4058efc97af1059ab3e41d";
      fetchSubmodules = false;
      sha256 = "sha256-oKvFN2K+ASlPNwj2rhptR/ErYgo6XKBPhXSZotDdCP0=";
    };
    date = "2023-12-23";
  };
  org-bullets = {
    pname = "org-bullets";
    version = "3623e86e0fa6d07f45042f7207fc333c014bf167";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "org-bullets.nvim";
      rev = "3623e86e0fa6d07f45042f7207fc333c014bf167";
      fetchSubmodules = false;
      sha256 = "sha256-aIEe1dgUmDzu9kl33JCNcgyfp8DymURltH0HcZfph0Y=";
    };
    date = "2024-02-21";
  };
  telescope-orgmode = {
    pname = "telescope-orgmode";
    version = "a8478496911e378868f44bd9fd5fd5ce5eeec57b";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "telescope-orgmode.nvim";
      rev = "a8478496911e378868f44bd9fd5fd5ce5eeec57b";
      fetchSubmodules = false;
      sha256 = "sha256-08QCcMm10XiCMkQfOdpAESck3k/O1PINqRjD+jwLusc=";
    };
    date = "2024-05-24";
  };
}
